- name: copy catalogue service to system directory
  ansible.builtin.template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: systemctl deamon reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: start and enable catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted # even app is not running, we can restart
    enabled: yes